sudo: required

services:
- docker

env:
  global:
  - secure: "eHLoemYocEBYOkJwZC75aWedgXtaKubGhBAo453OF8amiNhBpUz3k3YeLMdtT7RWqjtZS9Fnh96oqtn6aPuh+yrpzsQqwDcahuO0OsdRgp4n/4ltIfgpRTCl0FPfjVZtYuPWBh3XPfuzA5/yAjXKdUAxb6nUm6tqH2ZWl2MCLGpmKYQSpUBNypd4K4tr1DSefILwpYHmmHTWvB+T52Koq5Td4q2ZZ/72hj572iqHAbxdCQYyABGp8xk8dAl15YU6IIe5uKfCt+atTmFDe6G9ql9KKAlehYbNZ4qRFjuPUgt1JG9C908gZ78VhbHc9+xBvuYOfdahHrfSgdX4rPnPXpawJ/cGz57LbHcbp2kcYhcmGWUE+R4rdqwK48R5y6snL0bkIu738laNMkD4IVch5Q6KPngtqPuAcAfAsRbzkjm0VVGOKvMai4Ln6vjZpOjG/vfHL2X5YMp5xAcRdbgI6czu60SduXOHnr7oyyROilIH6cFDHgVCQajmobJ0oOuFewpmiCvv6xN8FSTELO4m9r4taXg+JRWai5VT14Y359ow8isvp85wJqTrIyo44CX7mbwumnCcPpQ0i3CFXheHCZnNTfoMJQXjPwo73KJVaZ51rfK4zHUXwXEijbnL/AgRZw3p5og/vBNEsM7+XKaBq49gs1DwyWT7UmHlmJUw0l0="
  - secure: "EVkOu/3QzGCTfbl62AbQciBmkMR84x6x46Vue40LEom1tv6125/ckn7PADdnDEbwAHVp/tIR3VyBeQT2/UYkTD8YGN7M5U05kMxbZ5SJENuh6pSV8ykD1bclBp4HzQNJHcAq9ENxeDspk1VgPbxzOYklmmS/g2UQIzSEdpbIhSchvUFWf8/RuT976AWUVsWA+8Chmg+HR/KB5Jzz1WzHZRTgn3weBcZ+t/mVTqW/5jl6FbdoV0apbytAyfWfvlOvGhgW70HK4dUUjsQG8SOi12X6tkohSJBHwxTpC0EWITp5jFEhCdCZOM9MUONB38BPhFZqobQxVntRW/aKgkWFlvMVZWPz0MbuLxGhPq+0y6n5zSsu6N4xFfaDpN+2mUawJERxFn9aKS4m4tVaCHZi65zGsuOSA/hdFonTOoM9fLVG7Ei26B76pejlupwTl+TTw/r/qHOyC1jWQc62tmjYwBP6mPUWQVHgvNqTpPCRq4Ud+3liXigUO427ekU4qwSPykw9NZ1SCa7oXhnF74xTCKlItFHJY8pMNTnVOmu4aF5vW1QDUy2pyxDhtRR7PeYqp3pqqNF8rVf6tOo/5SwnS2uWDC3/ITzR9gIJeKtHKA7RnCphzrdR+ZYnJpzoqMajkL/zC03V7hK6B64eiYOStYyWJHyjRqQ6kF89CdL3tB4="

script:

echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
export DOCKER_TAG="${TRAVIS_BRANCH/\//_}"
echo "Build image for tag ${DOCKER_TAG}";
docker pull wbaa/rokku-dev-apache-atlas:latest;
travis_wait 80 docker build -t wbaa/rokku-dev-apache-atlas:$DOCKER_TAG .;
docker push wbaa/rokku-dev-apache-atlas:$DOCKER_TAG;
docker tag wbaa/rokku-dev-apache-atlas:$DOCKER_TAG wbaa/rokku-dev-apache-atlas:latest;
docker push wbaa/rokku-dev-apache-atlas:latest;
